#!/usr/bin/php
<?php

$return = 0;

$output = array();
exec('git rev-parse --verify HEAD 2> /dev/null', $output, $return);

$against = '4b825dc642cb6eb9a060e54bf8d69288fbee4904'; // git empty tree
if ($return == 0) {
	$against = 'HEAD';
}

$changed_files = array();
exec("git diff-index --cached --name-status $against | egrep '^(A|M)' | awk '{print $2;}'", $changed_files);

$exit_status = 0;
foreach ($changed_files as $file) {
	if (preg_match('/\/ext\//', $file)) {
		// skip checks on .js files under an "/ext/" folder
		// @todo: maybe consider some kind of policy config?
		continue;
	}
	if (!preg_match('/\.js$/', $file)) {
		continue;
	}
	$return = 0;
	$output = array();
	exec('jshint '. escapeshellarg($file), $output, $return);
	if ($return == 0) {
		continue;
	}
	echo trim(implode("\n", $lint_output)) . "\n";
	$exit_status = 1;
}

exit($exit_status);