#!/usr/bin/php
<?php

$return = 0;

$output = array();
exec('git rev-parse --verify HEAD 2> /dev/null', $output, $return);

$against = '4b825dc642cb6eb9a060e54bf8d69288fbee4904'; // git empty tree
if ($return == 0) {
	$against = 'HEAD';
}

$changed_files = array();
exec("git diff-index --cached --name-status $against | egrep '^(A|M)' | awk '{print $2;}'", $changed_files);

function json_last_error_readable()
{
	$code = json_last_error();
	$constants = get_defined_constants(true);
	$json_errors = array();
	foreach ($constants["json"] as $name => $value) {
		$needle = "JSON_ERROR_";
		if ($value === $code && substr($name, 0, strlen($needle)) == $needle) {
			return $name;
		}
	}
	return "JSON_ERROR_NONE";
}

$exit_status = 0;
foreach ($changed_files as $file) {
	if (!preg_match('/\.json$/', $file)) {
		continue;
	}
	$contents = json_decode(file_get_contents($file));
	if (is_null($contents)) {
		echo "Syntax error in ".$file." (".json_last_error_readable().")\n";
		$exit_status = 1;
	}
}

exit($exit_status);