#!/usr/bin/php
<?php

if (in_array("--about", $argv)) {
	echo "Check PHP files for syntax errors";
	die;
}

$return = 0;

$output = array();
exec('git rev-parse --verify HEAD 2> /dev/null', $output, $return);

$against = '4b825dc642cb6eb9a060e54bf8d69288fbee4904'; // git empty tree
if ($return == 0) {
	$against = 'HEAD';
}

$changed_files = array();
exec("git diff-index --cached --name-status $against | egrep '^(A|M)' | awk '{print $2;}'", $changed_files);

$exit_status = 0;
foreach ($changed_files as $file) {
	if (!preg_match('/\.php$/', $file)) {
		continue;
	}
	$return = 0;
	$output = array();
	exec('php -l '. escapeshellarg($file), $output, $return);
	if ($return == 0) {
		continue;
	}
	echo trim(implode("\n", $lint_output)) . "\n";
	$exit_status = 1;
}

exit($exit_status);