#!/usr/bin/php
<?php

if (in_array("--about", $argv)) {
	echo "Run phpunit tests on code before commit (if phpunit.xml exists)";
	die;
}

$exit_status = 0;

if (file_exists("phpunit.xml")) {
	$return = 0;
	$output = array();
	exec("phpunit", $output, $return);
	if ($return != 0) {
		$exit_status = 1;
		echo trim(implode("\n", $output))."\n";
	}
}

exit($exit_status);